
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: ten
    password: 1q2w3e4r5t!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl 
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
      use-new-id-generator-mappings: false # 기본 전략 x, 프로젝트 코드에 선언된 넘버링 전략을 사용하겠다.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false
    
     
    
      